name: Build Emoji Map

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PYTHON_VERSION: "3.10.4"
            NODE_VERSION: "20"
            PROJECT_VERSION: "v0"
            MAP_DATA_NAME: "emojis_v0.json"
            MAP_DATA_URL: "https://drive.google.com/uc?id=18410XLDOgXxY5PHxn8IEIDytDgu81MB7"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REQUIREMENTS_FILE: "requirements_build.txt"
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ env.PYTHON_VERSION }}
            - name: Set up Node (for js-beautify)
              uses: actions/setup-node@v4
              with:
                node-version: ${{ env.NODE_VERSION }}
            - name: Install dependencies & Retrieve data
              working-directory: ${{ env.PROJECT_VERSION }}
              run: |
                python -m pip install --upgrade pip
                if [ -f ${{ env.REQUIREMENTS_FILE }} ]; then pip install -r ${{ env.REQUIREMENTS_FILE }}; fi
                mkdir retrieval/data && cd retrieval/data
                gdown ${{ env.MAP_DATA_URL }} -O ${{ env.MAP_DATA_NAME }}
            - name: Build Emoji Map
              working-directory: ${{ env.PROJECT_VERSION }}
              run: |
                python build_emoji_map.py ${{ env.MAP_DATA_NAME }}
            - name: Format HTML
              run: |
                npm install -g js-beautify
                js-beautify --type html -r -s 1 -m 0 *.html
            - name: Commit and push updated generated files
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"

                # Fetch and check out the pull request branch
                git fetch origin ${{ github.event.pull_request.head.ref }}
                git checkout ${{ github.event.pull_request.head.ref }}

                # Update the changed files
                git add emoji_map.html
                git add ${{env.PROJECT_VERSION}}/screenshots/1000_random.png
                git commit -m "Automatically updated generated files"

                # Pull the latest changes and rebase
                git pull --rebase origin ${{ github.event.pull_request.head.ref }}

                # Push the updated commit to the pull request branch
                git push origin HEAD:${{ github.event.pull_request.head.ref }}
