name: Pytest unittest coverage
on: [push, pull_request]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    env:
        PYTHON_VERSION: "3.10.4"
        PROJECT_VERSION: "v0"
        CODE_COVERAGE_PERCENT: 90
        HF_INFERENCE_TOKEN: ${{ secrets.HF_INFERENCE_TOKEN }}
        REQUIREMENTS_FILE: "requirements_unittest.txt"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        working-directory: ${{ env.PROJECT_VERSION }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libxml2-utils
          python -m pip install --upgrade pip
          if [ -f ${{ env.REQUIREMENTS_FILE }} ]; then pip install -r ${{ env.REQUIREMENTS_FILE }}; fi
          mkdir retrieval/data
      - name: Test with pytest
        working-directory: ${{ env.PROJECT_VERSION }}
        run: |
          coverage run -m pytest  -v -s && coverage xml
      - name: Coverage verification
        working-directory: ${{ env.PROJECT_VERSION }}
        run: |
          bash verify_unittest_coverage.sh ${{ env.CODE_COVERAGE_PERCENT }}
